serve:
  port: 8081

spring:
  datasource:
    url: ${DB_MYSQL_DATASOURCE_URL}
    user: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASSWORD}
    port: ${DB_MYSQL_PORT}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    clean-disabled: true
    validate-on-migrate: true

jwt:
  expiration: ${JWT_EXPIRATION}
  key: ${auth}